<p id="firstfooter">
<a href="http://validator.w3.org/check?uri=referer"><img src="images/xhtml-valid.gif" alt="Valid XHTML 1.1!"/></a>
<a href="http://jigsaw.w3.org/css-validator/check/referer"><img src="images/css.png" alt="Valid CSS!"/></a>
Contact : <a href="mailto:tangui.lepense@free.fr">tangui.lepense@free.fr</a> - Jabber : <a href="xmpp:Tangui@im.apinc.org">Tangui@im.apinc.org</a>
<br/>
<span style="font-size:0.7em">Merci à Link Mauve pour sa relecture, ses conseils et ses corrections.</span>
</p>

<p id="secondfooter">
<a style="float:left" rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/"><img
alt="Licence Creative Commons" style="border-width:0"
src="http://i.creativecommons.org/l/by-sa/3.0/88x31.png" /></a> Ce <span
xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/Text"
property="dct:title" rel="dct:type">tutoriel SVG</span> (texte et images
  d'exemple) de <a
xmlns:cc="http://creativecommons.org/ns#" href="http://svground.fr"
property="cc:attributionName" rel="cc:attributionURL">Tangui Le Pense</a> est
mis à disposition selon les termes de la <a rel="license"
href="http://creativecommons.org/licenses/by-sa/3.0/">licence Creative Commons
Paternité - Partage à l&#39;Identique 3.0 non transposé</a>. Basé(e) sur
une oeuvre à <a xmlns:dct="http://purl.org/dc/terms/" href="http://svground.fr"
rel="dct:source">svground.fr</a>.
</p>
